### PR TITLE
Fix for Issue #41

### PR DESCRIPTION
**Pull request by akssri**

### CODE REVIEW

**Comment by akssri** [comment]
@guicho271828 
The whitespace cleanup appears to be quite pointless. Is there someway to only merge the first commit ?

**Comment by guicho271828** [comment]
plz just revert, fix and force push the commit

**Comment by akssri** [comment]
Done.

**Comment by guicho271828** [comment]
could you also add a test case corresponding to #41 ?

**Comment by akssri** [comment]
Done.

**Comment by guicho271828** [comment]
thank you very much!

**Pull request merged**
