### PR TITLE
Some cleanups for ASDF 3.3

### PR DESCRIPTION
**Pull request by fare**

### CODE REVIEW

**Comment by guicho271828** [comment]
I saw lots of similar pullreqs of yours on other projects. Is there any reason you make keywords into strings? Isn't a formal (and brief) announcement on website+reddit more appropriate for such changes?

**Comment by fare** [comment]
I indeed started a document on this topic, but I haven't finalized it yet:
https://gitlab.common-lisp.net/asdf/asdf/blob/plan/doc/best_practices.md

**Comment by guicho271828** [comment]
just asking, but are you working as a group, i.e., does several lispers involved in developing the best practices? Im not saying it should already be a consensus, but a reviewer or two might help regulate it

**Comment by fare** [comment]
I admit I did it alone, especially since Robert had health issues and was not currently not available for much help. I do welcome merge requests on https://gitlab.common-lisp.net/asdf/asdf/merge_requests though.

**Pull request merged**
